### ISSUE TITLE
Undefined variable $resourcesOptions

### ISSUE THREAD

**Issue by Riko0** [mikaeljorhult/hydrofon#126] opened 2023-02-27 19:29 UTC
Hi @mikaeljorhult, thank you for this project it looks awesome

I am not good at php and i have a problem

When trying to create booking i get an error "Undefined variable $resourcesOptions"

![screenshot_hydrofon](https://user-images.githubusercontent.com/5251810/221663531-36a42785-3df9-4921-962c-5727b3b6ba0d.png)

Am i doing something wrong?

i think it is located in hydrofon\resources\views\bookings\create.blade.php

**Comment by mikaeljorhult** [comment] 2023-02-27 20:11
You're not doing anything wrong - that's caused by a typo from a recent refactor. I've pushed a fix and added tests to make sure it won't happen there again. Pull the changes to the master branch and you should be fine.

Thank you for reporting it!

**Closed by mikaeljorhult** 2023-02-27 20:11 UTC

**Comment by Riko0** [comment] 2023-02-27 20:13
At the same time i founded it and fixed in my cloned version
Thank you again!
